# input_folder: "../../data/data/Person/data/train"                         # Path to the image folder
input_folder: "/home/yang/data/smoke-fire-person-dataset/person/VisDrone/train/images"                         # Path to the image folder
output_folder: "./result"                                                 # Path to the output folder
# ground_truth_label_file: "../../data/data/Person/label/filter_train.txt"   # Path to the ground truth label file
ground_truth_label_file: "../bin/labels.txt"   # Path to the ground truth label file
model: "google/owlv2-large-patch14-ensemble"                              # Model name
engine_path: "../data/owlv2_image_encoder_large_patch14.engine"           # Path to the engine file
threshold: "0.01"                                                         # Threshold for the owl model (Try not to change this)
nms_threshold: 0.3                                                        # Non-maximum suppression threshold
iou_threshold: 0.7                                                        # Intersection over union threshold
prompt: "person"                                                          # Prompt for the model, this model is designed specifically for person detection